### ISSUE TITLE
I need help please and thank you.

### ISSUE THREAD

**Issue by Bozo9** [nyekuuu/Dorito-bot-discord.js#57]
Every time i run a command it responds with 2 messages, there a way i can fix it?

**Comment by nyekuuu** [comment]
I think I fixed this bug but if you're on windows try make sure there's only one instance of the bot running and when you want to close an instance of the bot press ctrl+c in the cmd window to completely end it.

**Comment by Bozo9** [comment]
It works, Thanks!
